In [1]:
# pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
# Exercise 1:
# Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

import numpy as np

#numpy array with numbers from 1 to 10
array = np.arange(1, 11)

#array into a 2x5 matrix
matrix = array.reshape(2, 5)
print(matrix)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# Exercise 2:
# Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

import numpy as np

# Create a numpy array with numbers from 1 to 20
array = np.arange(1, 21)

# Extract elements between the 5th and 15th index
extracted_elements = array[5:15]

print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15]


In [6]:
# Exercise 3:
"""Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then,
add a new item to the series with the key 'pears' and the value 4. """

import pandas as pd
data = {'apples': 3, 'bananas': 2, 'oranges': 1}

series = pd.Series(data)

series['pears'] = 4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
# Exercise 4:
# Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

import pandas as pd

data = { 'name': ['Anna', 'Annie', 'Dexter', 'Bobby', 'Sanya', 'Nancy', 'Jimmy', 'George', 'Bunny', 'Jenny'],
    'age': [25, 30, 22, 28, 35, 27, 29, 24, 26, 31],
    'gender': ['Female', 'Female', 'Male', 'male', 'Female', 'Female', 'Male', 'male', 'Male', 'Female']}

# DataFrame
df = pd.DataFrame(data)
print(df)

     name  age  gender
0    Anna   25  Female
1   Annie   30  Female
2  Dexter   22    Male
3   Bobby   28    male
4   Sanya   35  Female
5   Nancy   27  Female
6   Jimmy   29    Male
7  George   24    male
8   Bunny   26    Male
9   Jenny   31  Female


In [8]:
# Exercise 5:
"""Add a new column to the data frame created in question 4, called occupation.
The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe."""

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

# Add the new column to the DataFrame
df['occupation'] = occupations

# print updated DataFrame
print(df)

     name  age  gender  occupation
0    Anna   25  Female  Programmer
1   Annie   30  Female     Manager
2  Dexter   22    Male     Analyst
3   Bobby   28    male  Programmer
4   Sanya   35  Female     Manager
5   Nancy   27  Female     Analyst
6   Jimmy   29    Male  Programmer
7  George   24    male     Manager
8   Bunny   26    Male     Analyst
9   Jenny   31  Female  Programmer


In [9]:
# Exercise 6:
# Select the rows of the dataframe where the age is greater than or equal to 30.

# Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]

# Display the filtered DataFrame
print(filtered_df)

    name  age  gender  occupation
1  Annie   30  Female     Manager
4  Sanya   35  Female     Manager
9  Jenny   31  Female  Programmer


In [10]:
# Exercise 7:
# Convert this dataframe to a csv file and read that csv file, finally display the contents.

import pandas as pd

# Convert the DataFrame df to a CSV file
df.to_csv('dataframe.csv', index=False)

new_df = pd.read_csv('dataframe.csv')
print(new_df)

     name  age  gender  occupation
0    Anna   25  Female  Programmer
1   Annie   30  Female     Manager
2  Dexter   22    Male     Analyst
3   Bobby   28    male  Programmer
4   Sanya   35  Female     Manager
5   Nancy   27  Female     Analyst
6   Jimmy   29    Male  Programmer
7  George   24    male     Manager
8   Bunny   26    Male     Analyst
9   Jenny   31  Female  Programmer
